<?php

namespace App\Observers;

use App\Models\ProductionControlShift1;
use App\Jobs\GenerateProductionReports;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Bus;

class ProductionControlShift1Observer
{
    public function created(ProductionControlShift1 $model)
    {
        $this->appendToCsv($model);
    }

    public function updated(ProductionControlShift1 $model)
    {
        $this->appendToCsv($model);
    }

    protected function appendToCsv(ProductionControlShift1 $rec)
    {
        Log::info('ProductionControlShift1Observer: appendToCsv invoked', ['id' => $rec->id]);

        // If this create was initiated by the Filament UI, the Filament page
        // will dispatch the GenerateProductionReports job in afterCreate().
        // Skip dispatch here to avoid duplicate generation.
        if (app()->bound('creating_by_filament')) {
            Log::info('ProductionControlShift1Observer: skipping dispatch because create comes from Filament', ['id' => $rec->id]);
            return;
        }
        try {
            $monthNames = [1=>'januari','februari','maret','april','mei','juni','juli','agustus','september','oktober','november','desember'];

            $preferredExcelRoot = config('report.excel_root', 'Z:' . DIRECTORY_SEPARATOR . 'PROD' . DIRECTORY_SEPARATOR . 'REPORT PCS EXCEL');
            $forcePreferred = config('report.force_preferred', false);
            $fallbackSubdir = config('report.fallback_subdir', 'reports');

            // normalize path separators and trim
            $preferredExcelRoot = rtrim(str_replace(['\\', '/'], DIRECTORY_SEPARATOR, $preferredExcelRoot), DIRECTORY_SEPARATOR);

            $usePreferred = false;
            if ($preferredExcelRoot && is_dir($preferredExcelRoot) && is_writable($preferredExcelRoot)) {
                $usePreferred = true;
            } elseif ($preferredExcelRoot && ! $forcePreferred) {
                // try to create the preferred dir if possible
                if (! is_dir($preferredExcelRoot)) {
                    if (@mkdir($preferredExcelRoot, 0777, true)) {
                        $usePreferred = is_writable($preferredExcelRoot);
                    }
                }
            }

            if ($usePreferred) {
                $excelRoot = $preferredExcelRoot;
            } else {
                $excelRoot = storage_path('app' . DIRECTORY_SEPARATOR . $fallbackSubdir . DIRECTORY_SEPARATOR . 'excel');
                if (! is_dir($excelRoot)) {
                    if (! mkdir($excelRoot, 0777, true) && ! is_dir($excelRoot)) {
                        Log::warning("ProductionControlShift1Observer: failed to create fallback excel dir {$excelRoot}");
                        return;
                    }
                }
            }

            if (! is_writable($excelRoot)) {
                Log::warning("ProductionControlShift1Observer: excel root not writable: {$excelRoot}");
                return;
            }

            $recordDate = $rec->date ? Carbon::parse($rec->date) : Carbon::now();
            $monthName = $monthNames[(int) $recordDate->format('n')];
            $monthDir = $excelRoot . DIRECTORY_SEPARATOR . $monthName;
            if (! is_dir($monthDir)) {
                if (! mkdir($monthDir, 0777, true) && ! is_dir($monthDir)) {
                    Log::warning("ProductionControlShift1Observer: failed to create month dir {$monthDir}");
                    return;
                }
            }

            // Live export CSV disabled: we no longer write incremental live_export files here.
            // Per-month CSVs are generated by the GenerateProductionReports job.
            Log::info('ProductionControlShift1Observer: live export disabled, skipping csv append', ['id' => $rec->id]);

            // Attempt to generate PDF immediately for this single record.
            try {
                if (class_exists(GenerateProductionReports::class)) {
                    // Use dispatchSync to run job immediately without requiring queue worker
                    Bus::dispatchSync(new GenerateProductionReports([$rec->id]));
                    Log::info('ProductionControlShift1Observer: dispatched GenerateProductionReports', ['id' => $rec->id]);
                }
            } catch (\Throwable $e) {
                Log::warning('ProductionControlShift1Observer: failed to dispatch PDF generation: ' . $e->getMessage());
            }

        } catch (\Throwable $e) {
            Log::error('ProductionControlShift1Observer appendToCsv error: ' . $e->getMessage());
        }
    }
}
